#!/bin/sh

# Due to issues with NAnt <exec> task with svnadmin dump, an intermediary
# script is used with parameters generated by Subnant.  This dumps faster
# and overcomes a NAnt issue where stdout and stderr get lumped together.

SVNADMIN=$1
REPOS=$2
DUMPFILE=$3
REV=$4 $5
INCREMENTAL=$6
DELTAS=$7

$SVNADMIN dump $REPOS > $DUMPFILE $REV $INCREMENTAL $DELTAS
