@echo off

REM Due to issues with NAnt <exec> task with svnadmin dump, an intermediary
REM script is used with parameters generated by Subnant.  This dumps faster
REM and overcomes a NAnt issue where stdout and stderr get lumped together.

SET SVNADMIN=%1
SET REPOS=%2
SET DUMPFILE=%3
SET REV=%4 %5
SET INCREMENTAL=%6
SET DELTAS=%7

%SVNADMIN% dump %REPOS% > %DUMPFILE% %REV% %INCREMENTAL% %DELTAS%
